### ISSUE TITLE
Self-improvement section should be improved

### ISSUE THREAD

**Issue by Ruben172** [osucord/resources#31]
As it stands, the self-improvement section is very lacking. Only having two resources, one of which not fitting in the category that should be moved to misc instead. There should be more guides included for different goals that are worthwhile and that players have found valuable.

**Comment by ekgame** [comment]
Maybe `Shikke's Anti-Mindblock` should be moved to training tools and `khz's streaming guide` moved to misc, at least until we have more guides to include.

**Comment by ekgame** [comment]
Sure it is, why would you think it's not?

**Comment by Ruben172** [comment]
How does it train your skills? How does it make you learn how to play better? It’s nothing more than a tool to trick your brain so I don’t see how it would fit there.

**Comment by ekgame** [comment]
https://www.youtube.com/watch?v=uc99yWeP1h4 - DigitalHypno's video for how to breakdown osu! skills.

**Comment by ekgame** [comment]
Resolved by #48.
