### ISSUE TITLE
Website improvements/discord link embed

### ISSUE THREAD

**Issue by oinkrr** [osucord/resources#33]
Some small improvements for the https://resources.osucord.moe website/discord link embed:

- Add an appropriate color to the discord embed with a meta tag `<meta name="theme-color" content="#F472B6">`
![ImnQqf](https://github.com/user-attachments/assets/9cb7b897-2ef0-49a6-a566-17ffefb8e408)

- Add the resources logo from the readme to the website, as well as the discord embed
https://github.com/osucord/resources/blob/main/Assets/logo.png

The discord embed debugger can be used to test and check link embeds https://discord.com/developers/embeds

**Comment by jamesbt365** [comment]
This isn't completed, as #36 did not add the logo to the website as requested.
