### ISSUE TITLE
Tournaments section

### ISSUE THREAD

**Issue by ekgame** [osucord/resources#35]
This is a thread to submit links for a potential "Tournaments" section, to see if it's worth adding it.

**Comment by ekgame** [comment]
https://liquipedia.net/osu/Main_Page - Wiki for past and future tournaments documenting participants, map pools, matchups, prizes and more.

**Comment by ekgame** [comment]
https://osu.ppy.sh/community/tournaments - Official tournaments listing.

**Comment by ekgame** [comment]
https://osu.ppy.sh/community/forums/55 - Forum for the community run tournaments.

**Comment by ekgame** [comment]
https://osucollector.com/tournaments - Map pools from various concluded tournaments.

**Comment by Ruben172** [comment]
https://otu.stagec.xyz/ found on https://old.reddit.com/r/osugame/comments/1fc4acr/a_curated_collection_of_links_to_various_osu/lm76zmf/

**Comment by ekgame** [comment]
https://github.com/MiraiSubject/awesome-osu-tournaments
Either include the list itself, cherry-pick most relevant resources or both.

**Comment by ekgame** [comment]
Resolved by #48.
