### ISSUE TITLE
More prominant category for official links

### ISSUE THREAD

**Issue by ekgame** [osucord/resources#44]
There are some official links, but they are not very prominent and spread out. It would be better to consolidate them to a single category.

**Comment by oinkrr** [comment]
this is the official links we have right now. Those should be included

- [osu!wiki](https://osu.ppy.sh/wiki/en/Main_page) - Tons of different articles about osu!
- [osu! discord communities](https://osu.ppy.sh/wiki/en/Community/Discord_servers#official-osu!-server) - List of various discord servers made by the osu! community

**Comment by ekgame** [comment]
Resolved by #48.
