### ISSUE TITLE
A tablet area calculator based on specific thread and osu!playfield documentation

### ISSUE THREAD

**Issue by ghost** [osucord/resources#58]
I created a very simple website for calculating the ideal tablet area. I was sick of having bad aim in certain maps with certain patterns as I either flung my cursor too far, not enough, or missed the shape and direction of the pattern entirely as if I was drunk, and the calculator I made massively helped me with the former problems I had, especially around certain corners...that we don't wanna talk 'bout.

https://osu.ppy.sh/community/forums/topics/1995583?n=1 this is a thread my good friend made about it as they rly appreciated this website.

the website is hosted on GH Pages via Deno Deploy: https://osu-tableno.deno.dev/
the website has a github icon that leads to the source code: https://github.com/kawarbon/osu-tableno

Thank you!

**Comment by ekgame** [comment]
Hey, this looks pretty good, I'd approve adding it to the list, but I'd like to hear from James first - he's much more familiar with the minutia of tablets. 

Also, how hard do you think it would be to add a visualizer to overlay the full area with the selected percentage? That would immediately make it more useful from my perspective.

**Comment by jamesbt365** [comment]
I'm.. confused?

I don't get going off the playfield documentation, not providing anything *based* on that and then having the percentage be based off that? Do you have any reasoning? 100% shouldn't blindly be *less* than the actual size of the area without explaining why.

Also, your docs on Github do not work on multi monitor setups.

**Comment by jamesbt365** [comment]
Like, theres no *ideal* area, this calculator provides genuinely nothing new and just adds a new layer of confusion because it does not permit anything close to full area.

**Comment by kawarbon** [comment]
> Hey, this looks pretty good, I'd approve adding it to the list, but I'd like to hear from James first - he's much more familiar with the minutia of tablets.
> 
> Also, how hard do you think it would be to add a visualizer to overlay the full area with the selected percentage? That would immediately make it more useful from my perspective.

In an old attempt, i failed to visualise the area properly as I had no idea how I really wanted to represent, so I'll have to figure out a way to actually do it in a way similar to OTD.

**Comment by kawarbon** [comment]
> I'm.. confused?
> 
> I don't get going off the playfield documentation, not providing anything _based_ on that and then having the percentage be based off that? Do you have any reasoning? 100% shouldn't blindly be _less_ than the actual size of the area without explaining why.
> 
> Also, your docs on Github do not work on multi monitor setups.

I've never had osu! on multi-monitor and I have no player experience regarding how osu works over there, or how digital tablets run on those. Somebody with experience could fill me in with deets regarding that field.

Playfield documentation was initially used as baseline for "what do you really go for in the game" and a crudely written, incorrect early iteration of a visualiser that I was not happy with at all. the playfield *is* where all the objects are, and I find that going off of that seems to work fairly well for what 'an ideal' situational area would be, if we were to push an instruction in that direction.

Having a 16:9 (rectangular) area doesn't seem like an ideal choice when both sides are useless, and when the only part of the game you truly interact with is the low-res upscaled playfield in a sloppy square-ish shape.

Chances are i'm really wrong with assuming how the game works as I lack the experience regarding the internals of the game and how drawing tablets 'naturally' work on our hand-to-eye coordination. I mostly went off by the thread made by a user on the osu!forums. playfield docs were primarily a visualiser guide but was dropped when I had no idea how to actually visualise.

**Comment by kawarbon** [comment]
> Like, theres no _ideal_ area, this calculator provides genuinely nothing new and just adds a new layer of confusion because it does not permit anything close to full area. Which is a perfectly good area.

In an unpublic index.html prototype, i ACTUALLY had a full-area variant but i seem to have caused a problem in attempting to 'input' the calculations. I'll have to look into it again and perhaps make some of my own adjustments.

**Comment by jamesbt365** [comment]
> I've never had osu! on multi-monitor and I have no player experience regarding how osu works over there, or how digital tablets run on those. Somebody with experience could fill me in with deets regarding that field.

Do not recommend people turn on "Map absolute raw input to the osu! window" it should be disabled as it breaks multiple monitor setups, if you want to map the cursor to the game, simply map the display area in your driver to where the game is going to be.

> the playfield is where all the objects are, and I find that going off of that seems to work fairly well for what 'an ideal' situational area would be, if we were to push an instruction in that direction.

The area is attached to the display area you have set your tablet to, which for most people is the *entire* screen. Not the playfield.

> Having a 16:9 (rectangular) area doesn't seem like an ideal choice when both sides are useless, and when the only part of the game you truly interact with is the low-res upscaled playfield in a sloppy square-ish shape.

Once again most people map their tablet area to the entire display.

To users, it just looks you are throwing random values at them with no explanation for *why* the values are the way they are.

**Comment by kawarbon** [comment]
> Do not recommend people turn on "Map absolute raw input to the osu! window" it should be disabled as it breaks multiple monitor setups, if you want to map the cursor to the game, simply map the display area in your driver to where the game is going to be.

I did not recommend at all. If you read the README, it says I *tested* it on the following settings, and what I had toggled on in-game as those are what felt most ideal for me.

> The area is attached to the display area you have set your tablet to, which for most people is the entire screen. Not the playfield.
I'll take into consideration. I'm still new to these things. Could give me a break later on.

> To users, it just looks you are throwing random values at them with no explanation for why the values are the way they are.
I don't think most users care much about what goes on under the hood. They want results, not reasons.

**Comment by jamesbt365** [comment]
> I don't think most users care much about what goes on under the hood. They want results, not reasons.

But you're providing neither? Also a slider that goes to 100% but isn't 100% of the tablet is confusing, in my opinion.

**Comment by kawarbon** [comment]
> > I don't think most users care much about what goes on under the hood. They want results, not reasons.
> 
> But you're providing neither? (you're essentially saying "try this" but without explaining how you've come to that value, its no more than just a random number generator with a slider) Also a slider that goes to 100% but isn't 100% of the tablet is confusing, in my opinion.

I think I clarified already that I had screwed up porting over calculations from an unpublicised index.html prototype, which itself borrowed the things a user from the forums talked about. I'm already working on fixing this, which should be a relatively simple fix, albeit stupid.

I'm not good at explaining. I simply followed what a user 'researched' and tried to implement a form of it. Nothing more, nothing less. If that isn't enough, might have to make my own calculations.

**Comment by jamesbt365** [comment]
Feel free to open a pull request adding this to our list of resources when it clarifies what it does instead of just giving a blind slider, the tool should explain what its doing and why its doing it like it is.

It doesn't have to be long, but the explanation should be there for the users that want to read it. Right now this doesn't do anything but provide values without explaining why, and I think that should change before we include it.

**Comment by kawarbon** [comment]
> Feel free to open a pull request adding this to our list of resources when it clarifies what it does instead of just giving a blind slider, the tool should explain what its doing and why its doing it like it is.
> 
> It doesn't have to be long, but the explanation should be there for the users that want to read it. Right now this doesn't do anything but provide values without explaining why, and I think that should change before we include it.

where would you want the explanation? in README or code comments?

**Comment by jamesbt365** [comment]
> where would you want the explanation? in README or code comments?

Most users have no interest in the more technical GitHub page, so any comment will also have to be on the website (or the website should directly link to where it says what the tool does) a quick comment on the webpage somewhere should suffice.

**Comment by kawarbon** [comment]
> > where would you want the explanation? in README or code comments?
> 
> Most users have no interest in the more technical GitHub page, so any comment will also have to be on the website (or the website should directly link to where it says what the tool does) a quick comment on the webpage somewhere should suffice.

I've sent a commit, so I suppose now it is to open a PR and see what needs to be changed or added before merging, ya?
